# Generated by Django 3.1.4 on 2020-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='not_null', max_length=50),
            preserve_default=False,
        ),
    ]
