# Generated by Django 3.1.4 on 2021-01-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0002_userresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
