# Generated by Django 3.1.4 on 2021-02-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0002_question_correct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
