# Generated by Django 3.1.4 on 2021-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0004_auto_20210106_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.ManyToManyField(blank=True, related_name='questions_correct_answers', to='kit.Answer'),
        ),
    ]
