# Generated by Django 3.1.4 on 2021-01-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0006_question_answer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans',
            new_name='answer',
        ),
    ]
