# Generated by Django 3.1.4 on 2021-01-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0007_auto_20210106_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='user_answers',
            field=models.ManyToManyField(related_name='user_answers', to='kit.Answer'),
        ),
    ]
