# Generated by Django 3.1.4 on 2021-01-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0008_userresponse_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='weight',
            field=models.IntegerField(default=5, verbose_name='marks'),
        ),
    ]
